# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada7de7775abe754893c1daaf7a8498bab7fdf1f8cc54a50eadf7cc84da2878f1513b9b2310077cd7e6c673f29e69420f819e32da2a4c02c11270b3f9a191375

test:
  secret_key_base: d3a9a2142aebaeb6e187f45808d45db45718faf9aef41f7724c3cbfa64fb727f696531e904c531968c96bb59a78e06fd9ec19aa8655b19c39ed6589c32128073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
